blank_issues_enabled: true
contact_links:
  - name: ğŸ“œ Uygunsuz iÃ§eriÄŸi bildir
    url: https://github.com/${var.github_organization}/${REPO_NAME}/issues/new?template=report-abuse.yml
    about: Taciz, nefret sÃ¶ylemi veya davranÄ±ÅŸ kurallarÄ±na aykÄ±rÄ± iÃ§erikleri bildirmek iÃ§in kullanÄ±n.

  - name: âœ… Yeni GÃ¶rev OluÅŸtur
    url: https://github.com/${var.github_organization}/${REPO_NAME}/issues/new?template=task.yml
